### ISSUE TITLE
Problem with release 3.0.0

### ISSUE THREAD

**Issue by saraivinha85** [wso2-extensions/siddhi-io-rabbitmq#53]
**Description:**
Missing packages in 3.0.0 binary jar.

**Affected Product Version:**
3.0.0

**OS, DB, other environment details and versions:**    
All

**Steps to reproduce:**
The 3.0.0 jar release is missing the io.* packages. It only contains com.rabbitmq.*

**Comment by niveathika** [comment]
Thank you for pointing this out, @saraivinha85. We have fixed this in the latest release [v3.0.1](https://github.com/siddhi-io/siddhi-io-rabbitmq/releases/tag/v3.0.1)
